---
- name: set /etc/apt/apt.conf.d/50unattended-upgrades template
  template:
    src: etc-apt-apt.conf.d-50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  tags:
    - aspects_unattended_upgrades

- name: set /etc/apt/apt.conf.d/10periodic template
  template:
    src: etc-apt-apt.conf.d-10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
  tags:
    - aspects_unattended_upgrades

- name: set /etc/apt/apt.conf.d/20auto-upgrades template
  template:
    src: etc-apt-apt.conf.d-20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
  tags:
    - aspects_unattended_upgrades