---
- name: "Run aspects_unattended_upgrades tasks"
  when:
    - ansible_pkg_mgr == "apt"
    - aspects_unattended_upgrades_enabled
  include_tasks: "init.yml"
  tags:
    - aspects_unattended_upgrades